Imagine you’re a new security guard hired to protect a large apartment complex. Before you can secure individual apartments, you first need to know — which units are actually occupied? A vacant floor needs no patrolling. Nmap’s host discovery does exactly this: before scanning ports, it figures out which machines on a network are alive and worth investigating — whether you’re the guard, or someone trying to get past one.

Task — 2 Subnetworks

What is a network? A network is a group of computer linked together using a shared medium. Network works with an IP address, but there are a limited number of IP’s available, so to fix this issue, what we did was, divide an IP within a network giving a separate IP under the same network, this concept is known as subnetting. Think of it like a cake at a family gathering instead of buying a separate pastry for each of the 8 members, you get one cake and slice it into 8 pieces. One IP block, divided among many devices.

When Nmap scans a network, it’s looking across all those “slices” to find which devices are actually online, that’s host discovery.

Subnets with /16, which means that the subnet mask can be written as 255.255.0.0. This subnet can accommodate around 65,534 hosts.
Subnets with /24, which indicates that the subnet mask can be expressed as 255.255.255.0. This subnet can have around 254 hosts.
Now, instead of just having an IP address, devices have a physical address or a MAC address. So, when we are on a subnet, the scanner uses ARP (address resolution protocol), which maps the IPv4 address to the MAC address. ARP asks the “hey, who’s IP is this?” and gets a MAC address as a result and actually know that if there is a packet for this IP, I have to transfer to this MAC, and actually creates a mapping table for it.

It’s like having a nickname for your home, suppose your name for the world is “Hugh E. Rection”, your friends call you Hugh E. Rection, your girlfriend (Ok, sorry, forgot that you are single) calls you Hugh E. Rection but, in your home, everyone calls you “Bruce”, in this case when you network with someone outside your home network, you are called Hugh E. Rection which relates to IP address, but in your home, where you use MAC address, everyone calls you Bruce.

If you are in Network A, you can use ARP only to discover the devices within that subnet (10.1.100.0/24). Suppose you are connected to a subnet different from the subnet of the target system(s). In that case, all packets generated by your scanner will be routed via the default gateway (router) to reach systems on another subnet; however, ARP queries won’t be routed and therefore cannot cross the subnet router. ARP is a link-layer protocol, and ARP packets are bound to their subnet.

How many devices can see the ARP Request?

4

Did computer6 receive the ARP Request? (yea/nay)

nay

How many devices can see the ARP Request?

4

Did computer6 reply to the ARP Request? (yea/nay)

nay

Task — 3

ARP from Link Layer
ICMP from the Network Layer
TCP from the Transport Layer
UDP from the Transport Layer
If you want to ping a system on the same subnet, an ARP query should precede the ICMP Echo.

Although TCP and UDP are transport-layer protocols, for network scanning, a scanner can send a specially crafted packet to common TCP or UDP ports to check whether the target responds. This method is efficient, especially when ICMP Echo is blocked.

What type of packet did computer1 send before the ping?

ARP request

What type of packet did computer1 receive before it was able to send the ping?

ARP Response

How many computers responded to the ping request?

1

What is the name of the first device that responded to the first ARP Request?

router

What is the name of the first device that responded to the second ARP Request?

computer5

Send another Ping Request. Did it require new ARP Requests? (yea/nay)

nay

Task — 4

We can scan IP’s in the following ways:

Making a list.
Making a range
Subnet
What is the first IP address Nmap would scan if you provided 10.10.12.13/29 as your target?

10.10.12.8

How many IP addresses will Nmap scan if you provide the following range: 10.10.0–255.101–125?

6400

Task — 5

Remember our security guard analogy? Now, you were told by your boss you need to protect each house. The problem is you don’t know which floor has residents to protect as there may be some floors completely empty. So there should be a way of finding out which house has residents or as in case of networking, which hosts are online.

Write on Medium
There are 3 ways of finding if a host is online:

When a privileged user tries to scan targets on a local network (Ethernet), Nmap uses ARP requests. A privileged user is root or a user who belongs to sudoers and can run sudo.
When a privileged user tries to scan targets outside the local network, Nmap uses ICMP echo requests, TCP ACK (Acknowledge) to port 80, TCP SYN (Synchronise) to port 443, and ICMP timestamp requests.
When an unprivileged user tries to scan targets outside the local network, Nmap resorts to a TCP 3-way handshake by sending SYN packets to ports 80 and 443.
Nmap, by default, uses a ping scan to find live hosts, then proceeds to scan live hosts only. If you want to use Nmap to discover online hosts without port-scanning the live systems, you can issue nmap -sn TARGETS.

If you want Nmap only to perform an ARP scan without port-scanning, you can use nmap -PR -sn TARGETS, where -PR indicates that you only want an ARP scan.

How many hosts are found alive after scanning the CONNECTION_IP/24?

1

Task — 6

Suppose you went looking for residents inside each apartment, and some of them have closed doors and windows, they also have curtains so that no one can see inside. There are people still inside but you wont really know if there are residents inside or not, so you find another way, you ring the doorbell, if someone answers, there is at least one resident otherwise there is no one (considering the case the resident is not using the restroom when you rang the door bell).

Just like this, computers have firewalls that check each packet and either let them get forwarded or drop the packet. Firewalls are of two types, stateless and stateful, if it’s statefull, it will track the entire communication link, if not, you are in luck, because it will just look at an individual packet rather than connecting it with an existing link. MS windows now block the ICMP echo requests which are used for the ping tool. Even if you are on the same subnet, the packet might be dropped since ICMP echo preceds ARP query.

To use ICMP echo requests to discover live hosts, add the option -PE option. (Remember to add -sn if you don’t want to follow that with a port scan.)

Press enter or click to view image in full size

Adding the -PP option tells Nmap to use ICMP timestamp requests.

Press enter or click to view image in full size

Similarly, Nmap uses address mask queries (ICMP Type 17) and checks whether it gets an address mask reply (ICMP Type 18). This scan can be enabled with the option -PM.

Press enter or click to view image in full size

Although earlier scans showed at least 2 hosts are up, this scan returned none. The reason is that the target system or a firewall on the route is blocking this type of ICMP packet. Therefore, it is essential to learn multiple approaches to achieve the same result. If one packet type is blocked, we can always choose another to discover the target network and services.

What is the option required to tell Nmap to use ICMP Timestamp to discover live hosts?

-PP

What is the option required to tell Nmap to use ICMP Address Mask to discover live hosts?

-PM

What is the option required to tell Nmap to use ICMP Echo to discover live hosts?

-PE

Task — 7

Three-way handshake:

This does not mean three people shaking hands. Three way handshake happens in TCP. The first packet that gets sent is SYN, then SYN-ACK and at the last ACK.

We can send a packet with the SYN (Synchronise) flag set to TCP port 80 (80 by default) and wait for a response. An open port should reply with a SYN/ACK (Acknowledge); a closed port would result in an RST (Reset). In this case, we only check whether we receive a response to infer whether the host is up. The specific state of the port is not significant here.

Press enter or click to view image in full size

TCP ACK Ping

As you have guessed, this sends a packet with an ACK flag set. You must run Nmap as a privileged user to accomplish this. If you try it as an unprivileged user, Nmap will attempt a 3-way handshake.

By default, port 80 is used. The syntax is similar to TCP SYN ping. -PA should be followed by a port number, a port number range, a list, or a combination of them. For example, consider -PA21, -PA21-25 and -PA80,443,8080. If no port is specified, port 80 will be used.

Press enter or click to view image in full size

UDP Ping

Finally, we can use UDP to discover if the host is online. Unlike a TCP SYN ping, sending a UDP packet to an open port is not expected to elicit a reply. However, if we send a UDP packet to a closed UDP port, we expect to get an ICMP port-unreachable packet; this indicates that the target system is up and available.

Press enter or click to view image in full size

Which TCP ping scan does not require a privileged account?

TCP SYN Ping

Which TCP ping scan requires a privileged account?

TCP ACK Ping

What option do you need to add to Nmap to run a TCP SYN ping scan on the telnet port?

-PS23

Task — 8

Reverse DNS (rDNS) is the process of resolving an IP address to a hostname (the opposite of normal DNS). Instead of asking “What is the IP of example.com?”, you ask “What domain name is assigned to 10.200.6.15?”

In Nmap, using -R forces reverse lookups for all discovered hosts, while -n disables them. This helps identify system roles (e.g., mail.company.local, dc01.domain.com) and understand network structure during recon. However, rDNS records aren’t always configured or accurate, so results may be missing or misleading. It can also slightly slow scans due to additional DNS queries.

By default, Nmap will look up online hosts; however, you can use the option -R to query the DNS server even for offline hosts. If you want to use a specific DNS server, you can add the --dns-servers DNS_SERVER option.

We want Nmap to issue a reverse DNS lookup for all the possible hosts on a subnet, hoping to get some insights from the names. What option should we add?

-R

And that’s a wrap on this room!

If this helped you understand live host discovery even a little better, drop a clap (or fifty, I won’t judge). Got questions or I got something wrong? Leave a comment — I read them all.

See you in the next one.

— Harsh
